### PR TITLE
Dynamic Logo

### PR DESCRIPTION
**Pull request by benheller**
Our current logo is a static image. I thought it would be nice to replace this with a plain text + animated CSS version in order to optimize load times and add some pizzaz.

`https://yrevocnu.com/images/gbd_logo_uncovery_3.jpg`
image

I've kept the animation simple so as not to be overbearing, but we have some options when it comes to easing functions. Let me know if you'd like to explore that.

### CODE REVIEW

**Comment by benheller** [comment]
Note that this will need to be rebased once #4 lands.

**Comment by sbenthall** [comment]
running this locally I'm not seeing the animation. Is this supposed to show up in the upper left, in the header?

**Comment by benheller** [comment]
It is! I didn’t bother with adding browser-specific CSS prefixes to optimize compatibility (e.g. -webkit-transform), but I’m guessing that’s needed. There are some clever ways to do this using shims without junking up our main CSS files.

Could you provide your OS, OS version, browser, and browser version? I’ll cook up a fix and then ask you to re-test.

**Comment by benheller** [comment]
@sbenthall when you test, also make sure you've pulled the most recent code from this branch (it's been rebased) and run `bundle install` before running the app. 

I've tested and am not able to reproduce the issue in:

Chromium 81.0.4044.138 (Official Build) (64-bit)
Firefox 77.0.1 (64-bit)
Safari 13.1 (15609.1.20.111.8)

All on MacOS 10.15.4 (19E287)

**Comment by sbenthall** [comment]
ok it works for me now

**Review by sbenthall — APPROVED** [review]

**Pull request merged**
